version: '3'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      #target: development   name as form Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
      - app_static:/backend/django_app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_USER=myuser
      - DB_PASSWORD=mypw
    networks:
      - app-network

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypw
      MYSQL_ROOT_PASSWORD: myrootpw
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    command: ["sh", "-c", "sleep 10 && python manage.py migrate"]
      
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - .nginx/nginx.conf:/etc/nginx/nginx.conf
      - .nginx/ssl:/etc/nginx/ssl
      - app_static:/app/static
    depends_on:
      - projectwebsite1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
  app_static:
